export const userInfo = {
    name: "Francisco Murillo",
    email: "franc@gmail.com",
    image: "https://avatars.githubusercontent.com/u/105380?v=4",
    notes:[{
        id: 1,
        code: "EST101",
        note:90,
        title: "Estadistica",
        state: "AP",
        badge: "Excellent",
        badgeColor: "bg-green-500",
        modality: "Presential",
    },
{
        id: 2,
         code: "EST102",
        note:95,
        title: "Mathematics",
        state: "AP",
        badge: "Excellent",
        badgeColor: "bg-green-500",
        modality: "Presential",
    },
{
        id: 3,
         code: "EST103",
        note:80,
        title: "Estadistica",
        state: "AP",
        badge: "Very Good",
        badgeColor: "bg-blue-500",
        modality: "Virtual",
    },
{
        id: 4,
         code: "EST104",
        note:60,
        title: "Music",
        state: "RP",
        badge: "Reprobate",
        badgeColor: "bg-red-500",
        modality: "Presential",
    },
{
        id: 5,
         code: "EST105",
        note:74,
        title: "Programming",
        state: "AP",
        badge: "Aproved",
        badgeColor: "bg-yellow-500",
        modality: "Teleteaching",
    },
{
        id: 6,
        code: "EST106",
        note:89,
        title: "Networking",
        state: "AP",
        badge: "Very Good",
        badgeColor: "bg-blue-500",
        modality: "Virtual",
    }]
};

